[package]
name = "chartodo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
dirs = "5.0.1"
anyhow = "1.0.86"
serde_json = "1.0.122"
serde = { version = "1.0.204", features = ["derive"] }
comfy-table = "7.1.1"
chrono = "0.4.38"

[dev-dependencies]
assert_cmd = "2.0.15"
predicates = "3.1.2"
