[package]
name = "chartodo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
dirs = "5.0.1"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
